[general]
import = ["onedarkpro-onedark.toml"]
[window]
# decorations="Buttonless"
decorations="None"
# decorations="Transparent"
# opacity=0.1
# blur=true
option_as_alt="Both"
padding = { x = 0, y = 0 }
[scrolling]
history=100000
[font]
size = 16

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

