

### compinit {{

zstyle ':completion:*' menu select
zmodload zsh/complist
_comp_options+=(globdots)		# Include hidden files.

# Set custom location for the completion dump file
mkdir -p "$HOME/.local/state/zsh/"
ZCOMPDUMP_FILE="$HOME/.local/state/zsh/.zcompdump"

# Load compinit and run it with custom .zcompdump location
# Note: zsh will load from ZCOMPDUMP_FILE if it exists and
#       will auto regenerate when needed.
autoload -U compinit && compinit -d "$ZCOMPDUMP_FILE"

# Communicate when compinit cache has been updated
# Check time of last data modification, if it was in the last 2 seconds
# the cache has just been regenerated by zsh
if [[ $(stat -c %Y "$ZCOMPDUMP_FILE") -gt $(( $(date +%s) - 2 )) ]]; then
  echo "zsh completion cache has been regenerated"
fi

### }}

# Enable Bash-style completion in Zsh
autoload -Uz bashcompinit && bashcompinit

# gotask autocompletion
# NOTE: On Fedora the binary is go-task rather than task
if which go-task 1> /dev/null 2> /dev/null; then
  alias task="go-task"
fi
eval "$(task --completion zsh)"

